# NUMPY

In [1]:
### numpy 

import numpy as np

In [2]:
### creating the list 

python_list=[1,2,3,4,-5]

In [3]:
### displaying the python list

python_list

[1, 2, 3, 4, -5]

In [4]:
### converting the list into array

numpy_array=np.array(python_list)

In [5]:
### displaying the array which was converted from the list

numpy_array

array([ 1,  2,  3,  4, -5])

In [6]:
### printing the type of the variable

print(type(numpy_array))

<class 'numpy.ndarray'>


In [7]:
### shape attribute return the tuple representing the size of each dimension
### if it is 1d it just give one value that is the number of elements in the array

numpy_array.shape

(5,)

In [8]:
### length

len(numpy_array.shape)

1

In [9]:
### ndim attribute gives you the number of dimensions the array is
numpy_array.ndim

1

In [10]:
numpy_array.itemsize

4

**2D array**

In [11]:
### creating the 2d array

python_list_list=[[1,2,3],[4,5,6]]

In [12]:
python_list_list

[[1, 2, 3], [4, 5, 6]]

In [13]:
### converting the python list to array

numpy_array_array=np.array(python_list_list)

In [14]:
### displaying the 2d array

numpy_array_array

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
## the output values of the array is like (rows,columns) the shape attribute return the tuple representing the size of the array

numpy_array_array.shape

(2, 3)

In [16]:
### lenght of the tuple 

len(numpy_array_array.shape)

2

In [17]:
### finding the array dimension
numpy_array_array.ndim

2

***random values***

In [18]:
### arange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
### random value between 1 to 11

np.random.randint(1,11)

5

In [20]:
### set random values between 1 to 11 and here 5 represents give 5 values

np.random.randint(1,11,5)

array([9, 6, 3, 8, 5])

In [21]:
### random values in the 2d array format.

np.random.rand(2,2)

array([[0.97085761, 0.76556958],
       [0.0662595 , 0.00099561]])

In [22]:
### generating the random values from 0 to 5 with the 2d array format

np.random.randint(0,5,(2,2))

array([[2, 0],
       [0, 3]])

In [23]:
### generating the random values from 0 to 5 using size attribute

np.random.randint(5,size=(2,2))

array([[4, 3],
       [2, 0]])

In [24]:
### array of zeros
np.zeros(2)

array([0., 0.])

In [25]:
### array of zeros with int data type
np.zeros(2,dtype=int)

array([0, 0])

In [26]:
### array of ones 

np.ones(2)

array([1., 1.])

In [27]:
np.ones(2,dtype=int)

array([1, 1])

In [28]:
### finding the data type of the array 
numpy_array.dtype

dtype('int32')

In [29]:
value_array=np.array([1.3,5.4,8.6])

In [30]:
value_array

array([1.3, 5.4, 8.6])

In [31]:
### converting the float array to int array using [astype(int)]
value_array.astype(int)

array([1, 5, 8])

In [32]:
## slicing the array
arr=np.random.rand(5,5)
arr

array([[0.07313072, 0.99143374, 0.61617345, 0.11853288, 0.30947997],
       [0.25134677, 0.74432602, 0.11079172, 0.17840321, 0.04586177],
       [0.87807274, 0.2239112 , 0.83983522, 0.04880409, 0.60002831],
       [0.84246235, 0.94076064, 0.01104901, 0.51495171, 0.54307122],
       [0.47161687, 0.38401136, 0.59210115, 0.91230825, 0.69408818]])

In [33]:
### accessing the row
arr[4]

array([0.47161687, 0.38401136, 0.59210115, 0.91230825, 0.69408818])

In [34]:
arr[4,0:4]

array([0.47161687, 0.38401136, 0.59210115, 0.91230825])

In [35]:
### accessing the column
arr[:,4]

array([0.30947997, 0.04586177, 0.60002831, 0.54307122, 0.69408818])

In [36]:
### accessing the values
arr[0,0]

0.07313071841966756

In [37]:
### accessing the values
arr[1][1]

0.7443260156563574

In [38]:
### getting 4 rows and 5 columns
arr[:4]

array([[0.07313072, 0.99143374, 0.61617345, 0.11853288, 0.30947997],
       [0.25134677, 0.74432602, 0.11079172, 0.17840321, 0.04586177],
       [0.87807274, 0.2239112 , 0.83983522, 0.04880409, 0.60002831],
       [0.84246235, 0.94076064, 0.01104901, 0.51495171, 0.54307122]])

In [39]:
### getting 5 rows and 4 columns 
arr[:,:4]

array([[0.07313072, 0.99143374, 0.61617345, 0.11853288],
       [0.25134677, 0.74432602, 0.11079172, 0.17840321],
       [0.87807274, 0.2239112 , 0.83983522, 0.04880409],
       [0.84246235, 0.94076064, 0.01104901, 0.51495171],
       [0.47161687, 0.38401136, 0.59210115, 0.91230825]])

In [40]:
### getting 4 rows and 5 columns
arr[:4].shape

(4, 5)

In [41]:
### getting 3 rows and 4 columns
arr[1:4,0:4]

array([[0.25134677, 0.74432602, 0.11079172, 0.17840321],
       [0.87807274, 0.2239112 , 0.83983522, 0.04880409],
       [0.84246235, 0.94076064, 0.01104901, 0.51495171]])

In [42]:
arr[:-2]

array([[0.07313072, 0.99143374, 0.61617345, 0.11853288, 0.30947997],
       [0.25134677, 0.74432602, 0.11079172, 0.17840321, 0.04586177],
       [0.87807274, 0.2239112 , 0.83983522, 0.04880409, 0.60002831]])

In [43]:
value_value=np.random.randint(5,size=(6,8))

In [44]:
value_value

array([[0, 0, 3, 2, 1, 2, 4, 4],
       [2, 2, 1, 0, 0, 3, 3, 4],
       [2, 2, 0, 3, 1, 4, 2, 1],
       [4, 0, 3, 3, 0, 0, 0, 3],
       [2, 4, 4, 3, 2, 3, 0, 2],
       [4, 4, 4, 4, 0, 1, 4, 1]])

In [45]:
value_value_0=value_value[0]

In [46]:
value_value_0

array([0, 0, 3, 2, 1, 2, 4, 4])

In [47]:
values_012=(value_value_0==0) | (value_value_0==1) | (value_value_0==2)

In [48]:
values_012

array([ True,  True, False,  True,  True,  True, False, False])

In [49]:
value_value_0[values_012]

array([0, 0, 2, 1, 2])

# Transposing

In [50]:
marks=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [51]:
trans=np.array(marks)

In [52]:
trans

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
trans.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [54]:
### axis=1 it does row wise addition
trans.sum(axis=1)

array([ 6, 15, 24, 33])

In [55]:
### axis=0 it does column wise addition
trans.sum(axis=0)

array([22, 26, 30])

In [56]:
trans.transpose().sum(axis=1)

array([22, 26, 30])

In [57]:
trans

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**broadcasting**

In [58]:
### Broadcasting , perform element wise operation on array of different shapes and sizes

grace=np.array([1,2,3])

In [59]:
grace

array([1, 2, 3])

In [60]:
trans+grace

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [61]:
grace.shape

(3,)

In [62]:
grace.size

3

In [63]:
grace.ndim

1

In [64]:
### converting the 1 dimension array to 2 dimension array 

_grace1=np.reshape(grace,(3,1))
_grace1

array([[1],
       [2],
       [3]])

In [65]:
trans.transpose()+_grace1

array([[ 2,  5,  8, 11],
       [ 4,  7, 10, 13],
       [ 6,  9, 12, 15]])

In [66]:
#### converting the 1dimension array to 2dimension array 

grace2=grace[:, np.newaxis]
grace2

array([[1],
       [2],
       [3]])

In [67]:
#### using transpose for broadcasting 
grace3=np.array([[1,2,3,4]])
grace3

array([[1, 2, 3, 4]])

In [68]:
grace3.T

array([[1],
       [2],
       [3],
       [4]])

In [69]:
trans+grace3.T

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

# matrix multiplication

In [70]:
markss=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [71]:
markss

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
len(markss)

3

In [73]:
good=np.array([[0.4,0.2,0.2,0.2]])

In [74]:
weights=np.array([[0.4,0.2,0.2,0.2]]).transpose()

In [75]:
weights

array([[0.4],
       [0.2],
       [0.2],
       [0.2]])

In [76]:
len(weights)

4

In [77]:
### dot product of the matrix
np.dot(markss,weights)

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [78]:
###  matmul in numpy allows the matrix multiplication
np.matmul(markss,weights)

array([[ 2.2],
       [ 6.2],
       [10.2]])

In [79]:
### element wise multiplication is happening , this will happen when there is not transpose method.
markss*good

array([[0.4, 0.4, 0.6, 0.8],
       [2. , 1.2, 1.4, 1.6],
       [3.6, 2. , 2.2, 2.4]])

In [80]:
## identity matrix (diagonal elements are ones)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
## diagonal function ( creates the diagonal function with the values provided)
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [82]:
np.diag(a)

array([1, 2, 3])

**operations**

In [83]:
e=np.array([0,1,4,3])

In [84]:
## sin values of the e
np.sin(e)

array([ 0.        ,  0.84147098, -0.7568025 ,  0.14112001])

In [85]:
## log values of the e
np.log(e)

C:\Users\saik3\AppData\Local\Temp\ipykernel_1072\1702208384.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(e)


array([      -inf, 0.        , 1.38629436, 1.09861229])

In [86]:
## exponent values of e
np.exp(e)

array([ 1.        ,  2.71828183, 54.59815003, 20.08553692])

In [87]:
### logical and and or

d=np.array([1,1,0,0],dtype=bool)
r=np.array([1,0,1,0],dtype=bool)
np.logical_or(d,r)

array([ True,  True,  True, False])

In [88]:
np.logical_and(d,r)

array([ True, False, False, False])

In [89]:
### argmax value gives the index values of the highest element
np.argmax(e)

2

In [90]:
### argmin value gives the index values of the lowest element
np.argmin(e)

0

In [91]:
np.max(e)

4

In [92]:
np.min(e)

0

In [93]:
### standard deviation 
e.std()

1.5811388300841898

In [94]:
### tile
##this is used in broadcasting ,helps in replicating the values and helps in converting the 1dimension array to 2dimension array

g=np.tile(np.arange(0,40,10),(3,1))
g

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [95]:
f=np.array([[0,1,2]])
f.transpose()

array([[0],
       [1],
       [2]])

In [96]:
g+f.transpose()

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32]])

In [97]:
p=np.tile([1,2,3],(3,1))
p

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [98]:
### converting the 2dimension array to 1dimension array 
np.ravel(np.random.randint(1,10,size=(3,3)))

array([2, 6, 5, 8, 3, 1, 7, 2, 1])

In [99]:
### creating the tensors(3 dimensional array)
nigga=np.arange(4*3*2).reshape(4,3,2)
nigga

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [100]:
nigga[0,2,1]

5

In [101]:
faltuuu=np.array([1,2,5,7,3,12,3,6,7,2,1])
faltuuu

array([ 1,  2,  5,  7,  3, 12,  3,  6,  7,  2,  1])

In [102]:
 ##### unique function 
unique_element=np.unique(faltuuu)
unique_element

array([ 1,  2,  3,  5,  6,  7, 12])

In [103]:
len(faltuuu)

11

In [104]:
len(unique_element)

7

In [105]:
### linspace states that the number of values from the start to end should the value in the num

import numpy as np
np.linspace(2,20,num=10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [106]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96